# compose.yml
services:
  bot:
    image: miharooll/tg-bot-pro:latest   # ← именно образ из DockerHub
    container_name: tg-bot-pro
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   - TZ=Europe/Moscow
